version: "2"

services:
    alfresco:
        image: alfresco/alfresco-governance-repository-community:V3.3.0.x-latest
        mem_limit: 1500m
        restart: unless-stopped
        environment:
            JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8082/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false
                -Xms1500m -Xmx1500m
                "
        ports:
            - 127.0.0.1:8082:8080 #Browser port
        networks: 
            - spisum_network
        volumes:
            - alf-repo-data:/usr/local/tomcat/alf_data
            - ./alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
            - ./mimetypes-extension-map.xml:/usr/local/tomcat/shared/classes/alfresco/extension/mimetype/mimetypes-extension-map.xml

    postgres:
        image: postgres:12.1
        restart: unless-stopped
        mem_limit: 512m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 127.0.0.1:5432:5432
        networks: 
            - spisum_network
        volumes:
            - postgres-data:/var/lib/postgresql/data
            # only run if you start the container with a data directory that is empty
            - ./postgres-init:/docker-entrypoint-initdb.d

    solr6:
        image: alfresco/alfresco-search-services:1.4.1
        restart: unless-stopped
        mem_limit: 3g
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
            #HTTP by default
            - ALFRESCO_SECURE_COMMS=none
            - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
        ports:
            - 127.0.0.1:8083:8983 #Browser port
        networks: 
            - spisum_network
        volumes:
            - solr-data:/opt/alfresco-search-services/data
            
    activemq:
        image: alfresco/alfresco-activemq:5.15.8
        restart: unless-stopped
        mem_limit: 1g
        ports:
            - 127.0.0.1:8161:8161 # Web Console
            - 127.0.0.1:5672:5672 # AMQP
            - 127.0.0.1:61616:61616 # OpenWire
            - 127.0.0.1:61613:61613 # STOMP
        networks: 
            - spisum_network
            
volumes:
    alf-repo-data:
        external: true
    postgres-data:
        external: true
    solr-data:
        external: true   
    shared-file-store-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs

networks: 
    spisum_network:
        external: true